name: PR

on:
  pull_request:
    paths:
      - "demo-ui/src/**"

env:
  SPA_DIRECTORY: demo-ui/src

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  spa-lint:
    name: Lint SPA Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo SPA code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.SPA_DIRECTORY }}
          sparse-checkout-cone: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Lint SPA Code
        working-directory: ${{ env.SPA_DIRECTORY }}
        run: |
          npm ci
          npm run lint

  spa-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.SPA_DIRECTORY }}

    steps:
      - name: Checkout Repo SPA code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.SPA_DIRECTORY }}
          sparse-checkout-cone: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run E2E Tests
        run: |
          npx playwright install --with-deps
          npm run test:e2e
